services:
  blommunity-db:
    image: postgres:18-alpine
    container_name: blommunity-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - blommunity-db-volume:/var/lib/postgresql/data

volumes:
  blommunity-db-volume:
    name: blommunity-db-volume
